" plugins
execute pathogen#infect()
syntax on
filetype plugin indent on

" toggle NERDTree
nmap <C-n> :NERDTreeToggle %<CR>

" turning off compatible for eclim
set nocompatible

" CtrlP
" Ignore these directories
set wildignore+=*/build/**
set wildignore+=*/target/**
let g:ctrlp_cmd='CtrlP :pwd'
let g:ctrlp_working_path_mode = 0
set wildignore+=*pyc
" disable caching
"let g:ctrlp_use_caching=0
nmap <C-b> :CtrlPBuffer<CR>

" highlight search
set hlsearch

set autoread

" showing line numbers
set number

" tabs
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

" resolving backspace problem
set backspace=2

" mapping ^s to :w
nnoremap <C-s> :w<cr>

au FileType proto,php,sh,c,cpp,java set cindent autoindent

" vim-clang-format
augroup autoformat_settings
  autocmd FileType bzl AutoFormatBuffer buildifier
  autocmd FileType c,cpp,proto,javascript AutoFormatBuffer clang-format
  autocmd FileType dart AutoFormatBuffer dartfmt
  autocmd FileType go AutoFormatBuffer gofmt
  autocmd FileType gn AutoFormatBuffer gn
  autocmd FileType html,css,json AutoFormatBuffer js-beautify
  autocmd FileType java AutoFormatBuffer google-java-format
  autocmd FileType python AutoFormatBuffer yapf
  " Alternative: autocmd FileType python AutoFormatBuffer autopep8
augroup END


" bash-like command completion
set wildmode=longest,list,full
set wildmenu

" for wrapping Chinese UTF-8
set formatoptions+=mM

" utf8
set encoding=utf-8

" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)
" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)
