#!/bin/bash
INTERVAL=1
PATTERN=${1:-"eth0"}

RXB=0
TXB=0
for rxbytes in /sys/class/net/$PATTERN/statistics/rx_bytes ; do
  let RXB+=$(<$rxbytes)
done
for txbytes in /sys/class/net/$PATTERN/statistics/tx_bytes ; do
  let TXB+=$(<$txbytes)
done

sleep $INTERVAL

RXBN=0
TXBN=0
for rxbytes in /sys/class/net/$PATTERN/statistics/rx_bytes ; do
  let RXBN+=$(<$rxbytes)
done
for txbytes in /sys/class/net/$PATTERN/statistics/tx_bytes ; do
  let TXBN+=$(<$txbytes)
done

RXDIF=$(echo $(((RXBN - RXB) / $INTERVAL )))
TXDIF=$(echo $(((TXBN - TXB) / $INTERVAL )))

SPEEDU="B/s"
SPEEDD="B/s"
if [ $RXDIF -ge 1024 ]; then
	SPEEDD="KB/s"
	RXDIF=$(echo $((RXDIF / 1024 )) )
fi

if [ $TXDIF -ge 1024 ]; then
	SPEEDU="KB/s"
	TXDIF=$(echo $((TXDIF / 1024 )) )
fi

if [ $RXDIF -ge 1024 ]; then
	SPEEDD="MB/s"
	RXDIF=$(echo $((RXDIF / 1024 )) )
fi

if [ $TXDIF -ge 1024 ]; then
	SPEEDU="MB/s"
	TXDIF=$(echo $((TXDIF / 1024 )) )
fi

if [ $RXDIF -ge 1024 ]; then
	SPEEDD="GB/s"
	RXDIF=$(echo $((RXDIF / 1024 )) )
fi

if [ $TXDIF -ge 1024 ]; then
	SPEEDU="GB/s"
	TXDIF=$(echo $((TXDIF / 1024 )) )
fi

echo "$PATTERN D:$RXDIF$SPEEDD U:$TXDIF$SPEEDU"
