case "$OSTYPE" in
  darwin*)  OS='mac' ;;
  linux*)   OS='linux' ;;
  *)        OS='default' ;;
esac

if [[ "$OS" == 'mac' ]]; then
  alias vim='/usr/local/bin/vim'
  alias l='ls -CF'
  # Postgres
  export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin"
  # completions
  # ubuntu: moved to /etc/bash_completion.d/
  # https://git-scm.com/book/en/v1/Git-Basics-Tips-and-Tricks
  source ~/git-completion.sh
  # bazel build scripts:bash_completion
  source ~/bazel-complete.bash
  export PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
fi

export PS1='\[\e[7m\]\u@\h:\w\$\[\e[0m\] '
export CLICOLOR=1
export EDITOR='vim'
export PATH="$HOME/.local/bin:$HOME/bin:$PATH"

# Go
export PATH="/usr/local/go/bin:$PATH"
export GOPATH=$HOME/go
export PATH="$PATH:$GOPATH/bin"

# ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"
alias r='rails'

# tmux
alias mux='tmux'

# vim mode
set -o vi

# clear
alias c='clear'

# ^s
stty -ixon

# docker
alias dockerkillall='docker kill $(docker ps -q)'
alias dockercleanc='printf "\n>>> Deleting stopped containers\n\n" && docker rm $(docker ps -a -q)'
alias dockercleani='printf "\n>>> Deleting untagged images\n\n" && docker rmi $(docker images -q -f dangling=true)'
alias dockerclean='dockercleanc || true && dockercleani'

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# ssh forwarding
alias sa='echo "export SSH_AUTH_SOCK=$SSH_AUTH_SOCK" > ~/.auth_ssh'
alias la='. ~/.auth_ssh'

# bazel
alias cdb='cd $(bazel info workspace)'

# adb devices
alias adbd='while true; do date; adb devices; sleep 1; done'

alias a='source ~/.env/bin/activate'
alias da='deactivate'

export PATH="$HOME/.node/bin:$PATH"
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib/fst

alias ssh-nopass='ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no'

# vim -o
alias vs="vim -O"

# Add this to .bashrc or its equivalent
transfer() { if [ $# -eq 0 ]; then echo -e "No arguments specified. Usage:\necho transfer /tmp/test.md\ncat /tmp/test.md | transfer test.md"; return 1; fi
  tmpfile=$( mktemp -t transferXXX ); if tty -s; then basefile=$(basename "$1" | sed -e 's/[^a-zA-Z0-9._-]/-/g'); curl --progress-bar --upload-file "$1" "https://transfer.sh/$basefile" >> $tmpfile; else curl --progress-bar --upload-file "-" "https://transfer.sh/$1" >> $tmpfile ; fi; cat $tmpfile; rm -f $tmpfile; }
