case "$OSTYPE" in
  darwin*)  OS='mac' ;; 
  linux*)   OS='linux' ;;
  *)        OS='default' ;;
esac

if [[ "$OS" == 'mac' ]]; then
  alias vim='/usr/local/bin/vim'
  alias l='ls -CF'
  # Postgres
  export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin"
  # completions
  # ubuntu: moved to /etc/bash_completion.d/
  # https://git-scm.com/book/en/v1/Git-Basics-Tips-and-Tricks
  source ~/git-completion.sh
  # bazel build scripts:bash_completion
  source ~/bazel-complete.bash
fi

export PS1='\[\e[7m\]\u@\h:\w\$\[\e[0m\] '
export CLICOLOR=1
export EDITOR='vim'
export PATH="$HOME/bin:$PATH"

# Go
export PATH="/usr/local/go/bin:$PATH"
export GOPATH=$HOME/go
export PATH="$PATH:$GOPATH/bin"

# ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"
alias r='rails'

# tmux
alias mux='tmux'

# vim mode
set -o vi

# clear
alias c='clear'

# ^s
stty -ixon

# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

# docker
alias dockerkillall='docker kill $(docker ps -q)'
alias dockercleanc='printf "\n>>> Deleting stopped containers\n\n" && docker rm $(docker ps -a -q)'
alias dockercleani='printf "\n>>> Deleting untagged images\n\n" && docker rmi $(docker images -q -f dangling=true)'
alias dockerclean='dockercleanc || true && dockercleani'

# fix python
function frameworkpython {
    if [[ ! -z "$VIRTUAL_ENV" ]]; then
        PYTHONHOME=$VIRTUAL_ENV /usr/local/bin/python "$@"
    else
        /usr/local/bin/python "$@"
    fi
}

# added by Anaconda2 4.0.0 installer
# export PATH="/Users/linyinong/anaconda2/bin:$PATH"

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# ssh forwarding
alias setauth='echo "export SSH_AUTH_SOCK=$SSH_AUTH_SOCK" > ~/.auth_ssh'
alias loadauth='. ~/.auth_ssh'

# bazel
alias cdb='cd $(bazel info workspace)'

# adb devices
alias adbd='while true; do date; adb devices; sleep 1; done'
